openapi: 3.1.0
info:
  title: TalkItOut API
  version: 1.0.0
  description: AI-powered support system API for Singapore students
servers:
  - url: http://localhost:4000
    description: Development server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /auth/register:
    post:
      summary: Register new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                age:
                  type: integer
                  minimum: 10
                  maximum: 19
                school:
                  type: string
                guardianConsent:
                  type: boolean
                role:
                  type: string
                  enum: [student, counselor]
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                  accessToken:
                    type: string
                  refreshToken:
                    type: string

  /auth/login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful

  /chat/message:
    post:
      summary: Send chat message
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  maxLength: 2000
      responses:
        '200':
          description: Message sent
          content:
            application/json:
              schema:
                type: object
                properties:
                  userMessage:
                    type: object
                  aiMessage:
                    type: object

  /tasks:
    get:
      summary: Get user tasks
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Tasks retrieved
    post:
      summary: Create task
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                subject:
                  type: string
                priority:
                  type: string
                  enum: [low, med, high]
                dueAt:
                  type: string
                  format: date-time
      responses:
        '201':
          description: Task created

  /checkins:
    post:
      summary: Create check-in
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mood:
                  type: integer
                  minimum: 1
                  maximum: 5
                note:
                  type: string
      responses:
        '201':
          description: Check-in created

  /pomodoro/start:
    post:
      summary: Start Pomodoro session
      security:
        - bearerAuth: []
      responses:
        '201':
          description: Session started

  /risk/flags:
    get:
      summary: Get risk flags (counselor only)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Flags retrieved
